# Generated by Django 4.0.6 on 2022-07-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_studentpaymentsdone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentpaymentsdone',
        ),
    ]
